openapi: "3.0.3"
info:
  version: 1.0.0
  title: Employee Management API
servers:
  - url: http://employee-management.swagger.io/v1
paths:
  /employees:
    get:
      summary: List all employees
      operationId: listEmployees
      tags:
        - employees
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of Employees
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Emlpoyees"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create an Employee
      operationId: createEmployees
      tags:
        - employees
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /employees/{emlpoyeeId}:
    get:
      summary: Info for a specific Employee
      operationId: showEmlpoyeesById
      tags:
        - emlpoyees
      parameters:
        - name: emlpoyeeId
          in: path
          required: true
          description: The id of the emlpoyee to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Emlpoyee"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Emlpoyee:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Emlpoyees:
      type: array
      items:
        $ref: "#/components/schemas/Emlpoyee"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
